services:
  ecommerce-order-processing:
    build:
      context: ./ecommerce-order-processing
      dockerfile: Dockerfile
    container_name: ecommerce-order-processing
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - micro-service-network
    ports:
      - 3001:3001
    restart: always

  ecommerce-api:
    build:
      context: ./ecommerce-order-api
    container_name: ecommerce-api
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - micro-service-network    
    ports:
      - 3000:3000

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      - micro-service-network
networks:
  micro-service-network:
