services:
  ecommerce-order-processing:
    build:
      context: ./ecommerce-order-processing
      dockerfile: Dockerfile
    container_name: ecommerce-order-processing
    links:
      - db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - KAFKA=kafka:9092
    networks:
      - micro-service-network
    ports:
      - 3001:3001
    restart: always

  ecommerce-api:
    build:
      context: ./ecommerce-order-api
    container_name: ecommerce-api
    links:
      - db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - KAFKA=kafka:9092
    networks:
      - micro-service-network    
    ports:
      - 3000:3000

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      - micro-service-network

  zookeeper:
    image: 'wurstmeister/zookeeper'
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always
    networks:
      - micro-service-network      

  kafka:
    image: 'wurstmeister/kafka'
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092
      - KAFKA_LISTENERS=INSIDE://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181      
    restart: always
    networks:
      - micro-service-network
    links:
      - zookeeper

networks:
  micro-service-network:
